#!/usr/bin/env bash
# youtube-to-vault first-run setup wizard
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
CONFIG_FILE="$SCRIPT_DIR/config.yaml"
PROFILE_FILE="$SCRIPT_DIR/vault-profile.json"
SCAN_SCRIPT="$SCRIPT_DIR/.claude/skills/yt/scripts/scan_vault.py"

echo "=== youtube-to-vault setup ==="
echo ""

# 1. Check Python
if command -v python3 &>/dev/null; then
    PY_VERSION=$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
    PY_MAJOR=$(echo "$PY_VERSION" | cut -d. -f1)
    PY_MINOR=$(echo "$PY_VERSION" | cut -d. -f2)
    if [ "$PY_MAJOR" -ge 3 ] && [ "$PY_MINOR" -ge 10 ]; then
        echo "[OK] Python $PY_VERSION"
    else
        echo "[ERROR] Python 3.10+ required (found $PY_VERSION)"
        exit 1
    fi
else
    echo "[ERROR] Python 3 not found. Install Python 3.10+ first."
    exit 1
fi

# 2. Check uv
if command -v uv &>/dev/null; then
    echo "[OK] uv $(uv --version 2>/dev/null | head -1)"
else
    echo ""
    echo "uv is not installed. It's needed to run scripts without manual dependency management."
    read -rp "Install uv now? [Y/n] " install_uv
    if [[ "${install_uv:-Y}" =~ ^[Yy]$ ]]; then
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "[OK] uv installed"
        # Source the env so uv is available in this session
        export PATH="$HOME/.local/bin:$PATH"
    else
        echo "[WARN] Skipping uv install. You'll need it to run scripts."
    fi
fi

# 3. Ask vault path
echo ""
read -rp "Obsidian vault path (absolute): " VAULT_PATH
VAULT_PATH="${VAULT_PATH/#\~/$HOME}"

if [ ! -d "$VAULT_PATH" ]; then
    echo "[ERROR] Directory not found: $VAULT_PATH"
    exit 1
fi

if [ ! -d "$VAULT_PATH/.obsidian" ]; then
    echo "[WARN] No .obsidian/ folder found — this may not be an Obsidian vault."
    read -rp "Continue anyway? [y/N] " continue_anyway
    if [[ ! "${continue_anyway:-N}" =~ ^[Yy]$ ]]; then
        exit 1
    fi
fi

# 4. Output folder
echo ""
read -rp "Output folder for new notes (relative to vault root, empty = vault root): " OUTPUT_FOLDER

# 5. Daily notes
echo ""
read -rp "Daily notes folder (relative to vault root, empty = skip): " DAILY_FOLDER

# 6. Write config.yaml
echo ""
echo "Writing config.yaml..."

cat > "$CONFIG_FILE" << YAML
# youtube-to-vault configuration
# Generated by setup.sh

vault_path: "$VAULT_PATH"

output_folder: "$OUTPUT_FOLDER"

YAML

if [ -n "$DAILY_FOLDER" ]; then
    cat >> "$CONFIG_FILE" << YAML
daily_notes:
  folder: "$DAILY_FOLDER"
  date_format: "YYYY-MM-DD"
  insight_section: "## Insights"

YAML
fi

cat >> "$CONFIG_FILE" << 'YAML'
frontmatter:
  type: "reference"
  default_tags:
    - "youtube-import"
  include_source_url: true
  include_created: true
  include_updated: true

backlinks:
  auto_inject_outgoing: true
  prompt_before_incoming: true
  min_score: 3
  max_suggestions: 10

diagrams:
  enabled: false
  output_folder: "_media/excalidraw"
YAML

echo "[OK] config.yaml written"

# 7. Run vault scan
echo ""
echo "Scanning vault..."
uv run "$SCAN_SCRIPT" "$VAULT_PATH" > "$PROFILE_FILE"
echo "[OK] vault-profile.json written"

# 8. Print summary
echo ""
echo "=== Setup complete ==="
echo ""

TOTAL=$(python3 -c "import json; d=json.load(open('$PROFILE_FILE')); print(d['total_notes'])")
TAGS=$(python3 -c "import json; d=json.load(open('$PROFILE_FILE')); print(d['total_unique_tags'])")
LINK_STYLE=$(python3 -c "import json; d=json.load(open('$PROFILE_FILE')); print(d['link_style']['primary'])")
DIRS=$(python3 -c "
import json
d = json.load(open('$PROFILE_FILE'))
dirs = list(d['directories'].items())[:5]
for name, count in dirs:
    print(f'  {name}: {count} notes')
")

echo "Vault: $VAULT_PATH"
echo "Notes: $TOTAL"
echo "Tags:  $TAGS unique"
echo "Links: $LINK_STYLE"
echo ""
echo "Top folders:"
echo "$DIRS"
echo ""
echo "Next: Open this folder in Claude Code and paste a YouTube URL."
echo "      Claude will use /yt to process it into your vault."
